#include <iostream> 
using namespace std; 
int main()
{ try 
{ 
    throw 'a'; 
    } 
    catch (int param) 
    { 
        cout << "int exceptionn\n";
        } 
        catch (...) 
        { 
            cout << "default exceptionn\n"; 
            
        } 
        cout << "After Exception"; 
        return 0;
    
}
