#include <iostream>
using namespace std;
int main()
{
    int x=-1;
    try { 
        cout << "Inside try n\n";  
  if (x < 0) 
    { 
          cout<<"before throw\n";
          throw x; 
          cout << "After thrown\n"; 
         } 
    }
catch (int x)
{ 
   cout<<"Exception Caught n\n";
    cout << "After catch n"; 
return 0;
}
}
